# Generated by Django 3.1 on 2021-04-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
